services:
  grabengine:
    build: .
    container_name: grabengine
    environment:
      DATABASE_URL: postgresql://johndoe:randompassword@db:5432/mydb?schema=public
    depends_on:
      - db
    networks:
      - grabengine

  db:
    image: postgres:13
    container_name: grabengine-db
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - grabengine

networks:
  grabengine:

volumes:
  postgres-data: